#pragma config(Sensor, S1,     sLightLeft,     sensorI2CCustom9V)
#pragma config(Sensor, S2,     sTouch,         sensorTouch)
#pragma config(Sensor, S4,     sLightRight,    sensorI2CCustom9V)
#pragma config(Motor,  motorA,          mLeft,         tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          mCenter,       tmotorNXT, openLoop, reversed)
#pragma config(Motor,  motorC,          mRight,        tmotorNXT, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-lineleader.h"

float GetLFLeft();
float GetLFRight();

#define RELEASE
//#define DEBUG

task main()
{

	// init line followers
	LLinit(sLightLeft); 	// Set up Line Leader sensor type
	LLinit(sLightRight); 	// Set up Line Leader sensor type

	while (SensorValue(sTouch)== 0)
	{
		sleep (10);
	}
	// wake up line followers
	LLwakeUp(sLightLeft); 	// Wake sensor from sleep mode
	LLcalWhite(sLightLeft); 	// Set white threshold for light area
	LLwakeUp(sLightRight); 	// Wake sensor from sleep mode
	LLcalWhite(sLightRight); 	// Set white threshold for light area
	// -------------------------------------------------------------

	while (SensorValue(sTouch)== 1)
	{
		sleep (10);
	}

	int const vMax = 100;
	float es 			 = 0 ;
	float e 			 = 0;
	float eOld 		 = e;
	float rwLeft 	 = 0;
	float rwRight  = 0;
	int vLeft      = 0;
	int vRight     = 0;
	int vCenter    = 0;
	int v          = 0;
	float k			   = 18;

	es = GetLFLeft() / k - GetLFRight() / k;

	while(true)
	{
		rwLeft = GetLFLeft() / k;
		rwRight = GetLFRight()/ k;

		e = rwLeft - rwRight - es;

		float	u = (e  + (e - eOld ) * 5 ) * 1 ;

		eOld = e ;

		v = vMax - abs (u) ;

		vLeft   = v - u;
		vRight  = v + u;
		//vCenter = u;

#ifdef RELEASE
		motor[mLeft]   = vLeft;
		motor[mRight]  = vRight;
		motor[mCenter] = vCenter;
#endif
#ifdef DEBUG
		displayVariableValues(0,rwLeft);
		displayVariableValues(1,rwRight);
		displayVariableValues(2,u);
		displayVariableValues(3,vLeft);
		displayVariableValues(4,vRight);
		displayVariableValues(5,vCenter);
#endif
		if (SensorValue(sTouch)== 1) break;
		sleep (1);
	}
	LLsleep(sLightLeft); // Sleep to conserve power when not in use
	LLsleep(sLightRight); // Sleep to conserve power when not in use
}

float GetLFLeft()
{
	tByteArray rawLight;

	LLreadSensorRaw(sLightLeft, rawLight); // read the raw sensor data (8 bit data)
	return
	(
	rawLight[0] +
	rawLight[1] * 1.1 +
	rawLight[2] * 1.2 +
	rawLight[3] * 1.3 +
	rawLight[4] * 1.4 +
	rawLight[5] * 1.5 +
	rawLight[6] * 1.6 +
	rawLight[7] * 1.7
	);
}
float GetLFRight()
{
	tByteArray rawLight;
	LLreadSensorRaw(sLightRight, rawLight); // read the raw sensor data (8 bit data)
	return
	(
	rawLight[0] * 1.7 +
	rawLight[1] * 1.6 +
	rawLight[2] * 1.5 +
	rawLight[3] * 1.4 +
	rawLight[4] * 1.3 +
	rawLight[5] * 1.2 +
	rawLight[6] * 1.1 +
	rawLight[7]
	);

}
