#pragma config(Sensor, S1,     sLightLeft,     sensorI2CCustom9V)
#pragma config(Sensor, S2,     sTouch,         sensorTouch)
#pragma config(Sensor, S3,     sLightCenter,   sensorI2CCustom9V)
#pragma config(Sensor, S4,     sLightRight,    sensorI2CCustom9V)
#pragma config(Motor,  motorA,          mLeft,         tmotorNXT, openLoop, reversed)
#pragma config(Motor,  motorB,          mCenter,       tmotorNXT, openLoop, reversed)
#pragma config(Motor,  motorC,          mRight,        tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-lineleader.h"
float GetLFCenter();
float GetLFLeft();
float GetLFRight();

#define RELEASE
//#define DEBUG

task main()
{

	// init line followers
	LLinit(sLightLeft); 	// Set up Line Leader sensor type
	LLinit(sLightRight); 	// Set up Line Leader sensor type
	LLinit(sLightCenter); 	// Set up Line Leader sensor type

	while (SensorValue(sTouch)== 0)
	{
		sleep (10);
	}
	// wake up line followers
	LLwakeUp(sLightLeft); 	// Wake sensor from sleep mode
	LLcalWhite(sLightLeft); 	// Set white threshold for light area
	LLwakeUp(sLightRight); 	// Wake sensor from sleep mode
	LLcalWhite(sLightRight); 	// Set white threshold for light area
	// -------------------------------------------------------------

	while (SensorValue(sTouch)== 1)
	{
		sleep (10);
	}

	float vMax     = 100;
	float es 			 = 0 ;
	float e 			 = 0;
	float eOld 		 = e;
	//float esCenter = 0;
	float rwLeft 	 = 0;
	float rwRight  = 0;
	int vLeft      = 0;
	int vRight     = 0;
	int vCenter    = 0;
	int v          = 0;
	float k			   = 2;

	es = GetLFLeft() / k - GetLFRight() / k;
	//esCenter = GetLFCenter();
	//if (esCenter == 0) esCenter = 1;

	while(true)
	{

		rwLeft  = GetLFLeft() / k;
		rwRight = GetLFRight()/ k;

		e = rwLeft - rwRight - es;

		float	u = (e * 1 + (e - eOld ) *  4 ) * 0.15 ;

		eOld = e ;

		//v = vMax - abs (u) ;
		v = vMax - GetLFCenter() / 15 - abs (u) / 1.5;
		vLeft   = v + u ;
		vRight  = v - u ;
		vCenter = u / 1.5;

#ifdef RELEASE
		motor[mLeft]   = vLeft;
		motor[mRight]  = vRight;
		motor[mCenter] = vCenter;
#endif
#ifdef DEBUG
		displayVariableValues(0,rwLeft);
		displayVariableValues(1,rwRight);
		displayVariableValues(2,u);
		displayVariableValues(3,v);
		displayVariableValues(4,vLeft);
		displayVariableValues(5,vRight);
		displayVariableValues(6,vCenter);
#endif
		if (SensorValue(sTouch)== 1) break;
		sleep (1);
	}
	LLsleep(sLightLeft); // Sleep to conserve power when not in use
	LLsleep(sLightRight); // Sleep to conserve power when not in use
	LLsleep(sLightCenter); // Sleep to conserve power when not in use

}

float GetLFLeft()
{
	tByteArray rawLight;

	LLreadSensorRaw(sLightLeft, rawLight); // read the raw sensor data (8 bit data)
	return
	(
	rawLight[0] * 1.00 +
	rawLight[1] * 1.05 +
	rawLight[2] * 1.10 +
	rawLight[3] * 1.20 +
	rawLight[4] * 1.30 +
	rawLight[5] * 1.50 +
	rawLight[6] * 2.00 +
	rawLight[7] * 3
	);
}
float GetLFRight()
{
	tByteArray rawLight;
	LLreadSensorRaw(sLightRight, rawLight); // read the raw sensor data (8 bit data)
	return
	(
	rawLight[0] * 3.00 +
	rawLight[1] * 2.00 +
	rawLight[2] * 1.50 +
	rawLight[3] * 1.30 +
	rawLight[4] * 1.20 +
	rawLight[5] * 1.10 +
	rawLight[6] * 1.05 +
	rawLight[7] * 1.00
	);
}
float GetLFCenter()
{
	tByteArray rawLight;
	LLreadSensorRaw(sLightCenter, rawLight); // read the raw sensor data (8 bit data)
	return
	(
	rawLight[0] * 3.00 +
	rawLight[1] * 1.50 +
	rawLight[2] * 1.00 +
	rawLight[3] * 0.50 +
	rawLight[4] * 0.40 +
	rawLight[5] * 0.30 +
	rawLight[6] * 0.20 +
	rawLight[7] * 0.05
	)  ;
}
