#pragma config(Sensor, S1,     sLightLeft,     sensorI2CCustom9V)
#pragma config(Sensor, S2,     sCenterRight,   sensorLightActive)
#pragma config(Sensor, S3,     sCenterLeft,    sensorLightActive)
#pragma config(Sensor, S4,     sLightRight,    sensorI2CCustom9V)
#pragma config(Motor,  motorA,          mLeft,         tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          mCenter,       tmotorNXT, openLoop, reversed)
#pragma config(Motor,  motorC,          mRight,        tmotorNXT, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include	 "mindsensors-lineleader.h"

float GetLFLeft();
float GetLFRight();

#define RELEASE
#define DEBUG

task main()
{

	// init line followers
	LLinit(sLightLeft); 	// Set up Line Leader sensor type
	LLinit(sLightRight); 	// Set up Line Leader sensor type

	// wake up line followers
	LLwakeUp(sLightLeft); 	// Wake sensor from sleep mode
	LLcalWhite(sLightLeft); 	// Set white threshold for light area
	LLwakeUp(sLightRight); 	// Wake sensor from sleep mode
	LLcalWhite(sLightRight); 	// Set white threshold for light area
	// -------------------------------------------------------------

	// --------------------------------------------------------------

	float vMax     = 100;
	float es 			 = 0 ;
	float e 			 = 0;
	float eOld 		 = e;
	float esCenter = 0;
	float rwLeft 	 = 0;
	float rwRight  = 0;
	int vLeft      = 0;
	int vRight     = 0;
	int vCenter    = 0;
	int v          = 0;
	float k			   = 8;

	es = GetLFLeft() / k - GetLFRight() / k;
	esCenter = SensorValue(sCenter);
	if (esCenter == 0) esCenter = 1;

	while(true)
	{

		rwLeft  = GetLFLeft() / k;
		rwRight = GetLFRight()/ k;

		e = rwLeft - rwRight - es;

		float	u = (e * 1 + (e - eOld ) * 2 ) * 1 ;

		eOld = e ;

		//v = vMax - abs (u) ;
		v = vMax * ( esCenter / SensorValue(sCenter) ) - abs (u) / 2;
		vLeft   = v - u ;
		vRight  = v + u ;
		vCenter = u   ;

#ifdef RELEASE
		motor[mLeft]   = vLeft;
		motor[mRight]  = vRight;
		//motor[mCenter] = vCenter;
#endif
#ifdef DEBUG
		displayVariableValues(0,rwLeft);
		displayVariableValues(1,rwRight);
		displayVariableValues(2,u);
		displayVariableValues(3,v);
		displayVariableValues(4,vLeft);
		displayVariableValues(5,vRight);
		displayVariableValues(6,vCenter);
#endif
		if (SensorValue(sTouch)== 1) break;
		sleep (1);
	}
	LLsleep(sLightLeft); // Sleep to conserve power when not in use
	LLsleep(sLightRight); // Sleep to conserve power when not in use
}

float GetLFLeft()
{
	tByteArray rawLight;

	LLreadSensorRaw(sLightLeft, rawLight); // read the raw sensor data (8 bit data)
	return
	(
	rawLight[0] * 1.00 +
	rawLight[1] * 1.10 +
	rawLight[2] * 1.25 +
	rawLight[3] * 1.45 +
	rawLight[4] * 1.70 +
	rawLight[5] * 2.00 +
	rawLight[6] * 2.35 +
	rawLight[7] * 2.75
	);
}
float GetLFRight()
{
	tByteArray rawLight;
	LLreadSensorRaw(sLightRight, rawLight); // read the raw sensor data (8 bit data)
	return
	(
	rawLight[0] * 2.75 +
	rawLight[1] * 2.35 +
	rawLight[2] * 2.00 +
	rawLight[3] * 1.70 +
	rawLight[4] * 1.45 +
	rawLight[5] * 1.25 +
	rawLight[6] * 1.10 +
	rawLight[7] * 1.00
	);
}
