#pragma config(Sensor, S1,     sDistLeft,      sensorEV3_GenericI2C)
#pragma config(Sensor, S2,     sDistFront,     sensorEV3_GenericI2C)
#pragma config(Sensor, S3,     sDistRight,     sensorEV3_GenericI2C)
#pragma config(Sensor, S4,     sColor,         sensorEV3_Color)
#pragma config(Motor,  motorB,          mWheel,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mRear,         tmotorNXT, openLoop)
#pragma config(Motor,  motorD,          mFront,        tmotorNXT, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

////////////////////////////////////////////////////////////////
//
// rally motors
//
////////////////////////////////////////////////////////////////
// includes
//
//#include "mindsensors-ev3smux.h"
#include "mindsensors-irdist.h"

//--------------------------------------------
// wheel
#define WHEEL_ENCODER_MAX                145
#define WHEEL_SPEED						            60
#define WHEEL_DIST_MAX_ERROR            1200
#define WHEEL_INACCURACY_ENCODER           2
//dist
#define INIT_FRONT_DIST_MIN		           100
#define INIT_FRONT_DIST_MAX		           800
#define INIT_SIDE_DIST_MIN		           300
#define INIT_SIDE_DIST_MAX		          1500


//--------------------------------------------
// tasks
task wheelControl();
task getDist();
//--------------------------------------------
// functions
bool selfTest();
int normalizeSide(int dist);
int normalizeFront(int dist);
int getWheelEncoderByDistErr(int err);
bool isWheelCurrentEncoderOk(int currentEncoder, int targetEncoder);
//--------------------------------------------
// variables
int encRat				= 0;
int eDist 				= 0;
int eDistOld			= 0;
int frontDistMin  = INIT_FRONT_DIST_MIN;
int frontDistMax	= INIT_FRONT_DIST_MAX;
int sideDistMin		= INIT_FRONT_DIST_MIN;
int sideDistMax		= INIT_FRONT_DIST_MAX;
int distRight 		= 0;
int distLeft  		= 0;
int distFront 		= 0;


task main()
{

	//selfTest();

	sleep(100);
	startTask(getDist);
	sleep(100);
	startTask(wheelControl);
	sleep(100);

	while(true){
		encRat = (eDist * 1 + (eDist - eDistOld));
		eDistOld = eDist;
		displayBigTextLine(4, "%d", encRat);
		sleep(100);
	}
}

task getDist(){

	ubyte address = 0x02;

	string type1 = MSDISTreadModuleType(sDistFront, address);
	string type2 = MSDISTreadModuleType(sDistRight, address);
	string type3 = MSDISTreadModuleType(sDistLeft,  address);

	while(true){
		distLeft  = normalizeSide(MSDISTreadDist(sDistLeft, address));
		sleep(10);
		distRight = normalizeSide(MSDISTreadDist(sDistRight, address));
		sleep(10);
		distFront = normalizeFront(MSDISTreadDist(sDistFront, address));
		eDist 		= distLeft - distRight;
		sleep(10);
	}
}

int normalizeFront(int dist){
	if(dist < frontDistMin) return frontDistMin;
	if(dist > frontDistMax) return frontDistMax;
	return dist;
}

int normalizeSide(int dist){
	if(dist < sideDistMin) return sideDistMin;
	if(dist > sideDistMax) return sideDistMax;
	return dist;
}

task wheelControl()
{
	//int enc 	= 0;
	//int fEnc 	= 0;

	nMotorEncoder[mWheel] = 0;

	while(true){
		int targetEncoder = getWheelEncoderByDistErr(encRat);
		while ( ! isWheelCurrentEncoderOk( nMotorEncoder[mWheel] , targetEncoder ))
		{
			motor[mWheel] = -1 * sgn( nMotorEncoder[mWheel] - targetEncoder  ) * WHEEL_SPEED;
			targetEncoder = getWheelEncoderByDistErr(encRat);
			sleep(3);
		}
		motor[mWheel] = 0;
		sleep(10);
	}
}

bool isWheelCurrentEncoderOk(int currentEncoder, int targetEncoder)
{
	int t = currentEncoder - targetEncoder;
	return (abs(t) <= WHEEL_INACCURACY_ENCODER) ;
}

int getWheelEncoderByDistErr(int err)
{
	if (err > WHEEL_DIST_MAX_ERROR) err = WHEEL_DIST_MAX_ERROR;
	long t = WHEEL_ENCODER_MAX * err ; // protectes int overflow
	return -1 * (t / WHEEL_DIST_MAX_ERROR);
}

//--------------------------
bool selfTest()
{
	clearDebugStream();
 	writeDebugStreamLine("--isWheelCurrentEncoderOk()-- ");

	if ( ! isWheelCurrentEncoderOk(10, 0)) setException(1);


	return true;

}
