#pragma config(Sensor, S1,     sd1,            sensorI2CCustomFastSkipStates9V)
#pragma config(Sensor, S2,     sd2,            sensorI2CCustomFastSkipStates9V)
#pragma config(Sensor, S3,     sd3,            sensorI2CCustomFastSkipStates9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-irdist.h"


#define DEBUG

task carCounterZoneA();
task carCounterZoneB();
task carCounterZoneC();

#ifdef DEBUG
task displayInfo();
#endif
int zoneA = 0;
int zoneB = 0;

const int dis1 =150;
const int intervalSmall = 10;
const int intervalLong = 20;
task main()
{
	startTask(carCounterZoneA);
	startTask(carCounterZoneB);
	startTask(carCounterZoneC);
#ifdef DEBUG
	startTask(displayInfo);
#endif
	while(true)
	{
		sleep(100);
	}
}

task carCounterZoneA()
{
	while(true)
	{
		while( MSDISTreadDist(sd1) > dis1)
		{
			sleep(intervalLong);
		}
		while( MSDISTreadDist(sd1) < dis1)
		{
			sleep(intervalSmall);
		}
		zoneA++;
	}
}

task carCounterZoneB()
{
	while(true)
	{
		while( MSDISTreadDist(sd2) > dis1)
		{
			sleep(intervalLong);
		}
		while( MSDISTreadDist(sd2) < dis1)
		{
			sleep(intervalSmall);
		}
		zoneA--;
		zoneB++;
	}
}

task carCounterZoneC()
{
	while(true)
	{
		while( MSDISTreadDist(sd3) > dis1)
		{
			sleep(intervalLong);
		}
		while( MSDISTreadDist(sd3) < dis1)
		{
			sleep(intervalSmall);
		}
		zoneB--;
	}
}

task displayInfo()
{
	while(true)
	{
		displayBigTextLine(1,"A= %d",zoneA);
		displayBigTextLine(4,"B= %d",zoneB);
		sleep(100);
	}
}
