#pragma config(Sensor, S4,     sLightLeft,     sensorI2CCustom9V)
#pragma config(Sensor, S3,     sLightLeft2,    sensorI2CCustom9V)
#pragma config(Sensor, S2,     sLightRight2,   sensorI2CCustom9V)
#pragma config(Sensor, S1,     sLightRight,    sensorI2CCustom9V)
#pragma config(Motor,  motorB,          mLeft,         tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          mRight,        tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-lineleader.h"
#include "mindsensors-lightsensorarray.h"

// time: 	    08:20 - 08:40 (left) 8:60 - 8:80 (right) fast
// direction: left
// motors: 	  2
// ger: 	    direct
// tire:      \__/ #61481 + #56145c04

#define Max(x, y) (((x) > (y)) ? (x) : (y))
#define Min(x, y) (((x) < (y)) ? (x) : (y))

#define RELEASE
//#define DEBUG

int getRWRight();
int getRWLeft();
void calibrate ();
void waitTouchRelease();
//-------------------
/*
float const KL0 = 1.00;
float const KL1 = 1.00;
float const KL2 = 1.00;
float const KL3 = 1.00;
float const KL4 = 1.00;
float const KL5 = 1.00;
float const KL6 = 1.00;
float const KL7 = 1.00;
*/
//--------------------
int vBase 			= 50;
int const vMax  = 100;
int const vAlert= 50;
int const vMin	= 15;
int const maxI	= 15;
float const k 	= 38;
float const slowDown = 0.75;
int iAlert			= 0;
bool leftAlert  = false;
bool rightAlert = false;
//--------------------
task speedUp()
{
	int vFinish        = vBase;
	int const vStart   = 30;
	int const tSpeedUp = 600;
	int tSleep = tSpeedUp / ( vFinish - vStart );

	for ( int i = vStart ; i <= vFinish ; i++ )
	{
		vBase = i ;
		sleep(tSleep);
	}
}

//--------------------
task main()
{

	LLinit(sLightLeft); 	// Set up Line Leader sensor type
	LLinit(sLightRight); 	// Set up Line Leader sensor type
	MSLSAinit(sLightLeft2); 	// Set up Line Leader sensor type
	MSLSAinit(sLightRight2); 	// Set up Line Leader sensor type
	_lineLeader_cmd(sLightLeft, 'E'); // European frequency compensation
	_lineLeader_cmd(sLightRight, 'E'); // European frequency compensation
	MSLSAsetEU(sLightLeft2); // European frequency compensation
	MSLSAsetEU(sLightRight2); // European frequency compensation

	calibrate();
	waitTouchRelease();
	startTask(speedUp);

	int e       		= 0;
	int eOld 				= e;
	int rwLeft  		= getRWLeft();
	int rwRight 		= getRWRight();
	int es 					= 0; // rwLeft - rwRight;
	float i 				= 0;
	int 	v 				= 0 ;
	int   u					= 0 ;
	int vLeft 			= 0;
	int vRight 			= 0;
	long iSpeed     = 0;
	leftAlert  			= false;
	rightAlert 			= false;
	tByteArray rawLightLeft;
	tByteArray rawLightLeft2;
	tByteArray rawLightRight;
	tByteArray rawLightRight2;

	while(true)
	{
		//------------
		LLreadSensorRaw(sLightLeft, rawLightLeft);
		MSLSAreadSensors(sLightLeft2, &rawLightLeft2[0]);

		rwLeft=
		(
		Min(rawLightLeft[0], rawLightLeft2[0]) +
		Min(rawLightLeft[1], rawLightLeft2[1]) +
		Min(rawLightLeft[2], rawLightLeft2[2]) +
		Min(rawLightLeft[3], rawLightLeft2[3]) +
		Min(rawLightLeft[4], rawLightLeft2[4]) +
		Min(rawLightLeft[5], rawLightLeft2[5]) +
		Min(rawLightLeft[6], rawLightLeft2[6]) +
		Min(rawLightLeft[7], rawLightLeft2[7])
		);
		if ((Min(rawLightLeft[7], rawLightLeft2[7]) < 10) && (Min(rawLightLeft[0], rawLightLeft2[0]) > 10)) rwLeft = rwLeft * -1;
		//-----------------
		LLreadSensorRaw(sLightRight, rawLightRight);
		MSLSAreadSensors(sLightRight2, &rawLightRight2[0]);

		rwRight =
		(
		Min(rawLightRight[0], rawLightRight2[0]) +
		Min(rawLightRight[1], rawLightRight2[1]) +
		Min(rawLightRight[2], rawLightRight2[2]) +
		Min(rawLightRight[3], rawLightRight2[3]) +
		Min(rawLightRight[4], rawLightRight2[4]) +
		Min(rawLightRight[5], rawLightRight2[5]) +
		Min(rawLightRight[6], rawLightRight2[6]) +
		Min(rawLightRight[7], rawLightRight2[7])
		);
		if ((Min(rawLightRight[0], rawLightRight2[0]) < 10) && (Min(rawLightRight[7], rawLightRight2[7]) > 10)) rwRight = rwRight  * -1;
		//-------------
		if (rightAlert == false)
		{
			if (((rawLightLeft[7] < 20) && ((rawLightLeft[1] > 40) || (rawLightLeft[0] > 40))) ||
				  ((rawLightLeft2[7] < 20) && ((rawLightLeft2[1] > 40) || (rawLightLeft2[0] > 40)))) leftAlert = true;
	   }
			if (leftAlert && (iAlert > 0)) leftAlert = ((rawLightLeft2[4] > 20) &&
			(rawLightLeft2[3] > 20) &&
		(rawLightLeft2[2] > 20) &&
		(rawLightLeft2[1] > 20) &&
		(rawLightLeft2[0] > 20) &&
		(rawLightRight2[0] > 20) &&
		(rawLightRight2[1] > 20) &&
		(rawLightRight2[2] > 20) &&
		(rawLightRight2[3] > 20) &&
		(rawLightRight2[4] > 20) &&
		(rawLightRight2[5] > 20) &&
		(rawLightRight2[6] > 20) &&
		(rawLightRight2[7] > 20));
		if (leftAlert) rightAlert = false;

		if (leftAlert == false)
		{
			if (((rawLightRight[0] < 20) && ((rawLightRight[6] > 40) || (rawLightRight[7] > 40))) ||
			    ((rawLightRight2[0] < 20) && ((rawLightRight2[6] > 40) || (rawLightRight2[7] > 40)))) rightAlert = true;
		}
		if (rightAlert && (iAlert > 0)) rightAlert = ((rawLightRight2[3] > 20) &&
			(rawLightRight2[4] > 20) &&
		(rawLightRight2[5] > 20) &&
		(rawLightRight2[6] > 20) &&
		(rawLightRight2[7] > 20) &&
		(rawLightLeft2[0] > 20) &&
		(rawLightLeft2[1] > 20) &&
		(rawLightLeft2[2] > 20) &&
		(rawLightLeft2[3] > 20) &&
		(rawLightLeft2[4] > 20) &&
		(rawLightLeft2[5] > 20) &&
		(rawLightLeft2[6] > 20) &&
		(rawLightLeft2[7] > 20));
		if (rightAlert) leftAlert = false;
		//--------------
		e = rwLeft - rwRight - es;

		if (leftAlert)
		{
			vLeft  = vMin;
			vRight = vAlert ;
			iAlert ++;
		}
		else if (rightAlert)
		{
			vLeft  = vAlert;
			vRight = vMin;
			iAlert ++;
		}
		else
		{
			if ( iAlert != 0 )
			{
				i = 0;
				iSpeed = 0;
			}

			i = i + e / 2500;
			if ( fabs(i) > maxI ) i = sgn(i) * maxI ;
			u = (e * 1  + (e - eOld ) * 7) / k  + i;

			v = (vBase - abs (u) * slowDown ) ;

			vLeft = v + u;
			vRight = v - u;

			iAlert = 0;
		}

		eOld = e ;

		if (vLeft  < vMin)  vLeft  = vMin;
		if (vRight < vMin)  vRight = vMin;
		if (vLeft  > vMax)  vLeft  = vMax;
		if (vRight > vMax)  vRight = vMax;

#ifdef RELEASE
		motor[mLeft]  = vLeft;
		motor[mRight] = vRight;
#endif
#ifdef DEBUG
		displayTextLine(0,"rwL %d",rwLeft);
		displayTextLine(1,"rwR %d", rwRight);
		displayTextLine(2,"lAlert %d", leftAlert);
		displayTextLine(3,"rAlert %d",rightAlert);
		displayTextLine(4,"e %d",e);
		displayTextLine(5,"u %d",u);
		displayTextLine(6,"vLeft %d",vLeft);
		displayTextLine(7, "vRight %d",vRight);
#endif
		sleep (1);
		//if (SensorValue(sTouch) == 1) break;
	}
	LLsleep(sLightLeft);  // Sleep to conserve power when not in use
	MSLSASleep(sLightLeft2);  // Sleep to conserve power when not in use
	LLsleep(sLightRight); // Sleep to conserve power when not in use
	MSLSASleep(sLightRight2); // Sleep to conserve power when not in use
}

//---------------------------------

void calibrate ()
{
	displayBigTextLine(4, "  WHITE");

	while(true)
	{
		if (nNxtButtonPressed == 3)
		{
			while (nNxtButtonPressed == 3)
			{
				sleep (10);
			}
			break;
		}
		sleep (10);
	}
	LLcalWhite(sLightLeft);
	MSLSAcalWhite(sLightLeft2);

	LLcalWhite(sLightRight);
	MSLSAcalWhite(sLightRight2);

	playSound(soundBlip);

	displayBigTextLine(4, "   Done");

	sleep(1000);

	displayBigTextLine(4, "FAR BLACK");

	while(true)
	{
		if (nNxtButtonPressed == 3)
		{
			while (nNxtButtonPressed == 3)
			{
				sleep (10);
			}
			break;
		}
		sleep (10);
	}
	MSLSAcalBlack(sLightLeft2);
	MSLSAcalBlack(sLightRight2);

	playSound(soundBlip);

	displayBigTextLine(4, "  Done");

	sleep(1000);

		displayBigTextLine(4, "NEARBY BLACK");

	while(true)
	{
		if (nNxtButtonPressed == 3)
		{
			while (nNxtButtonPressed == 3)
			{
				sleep (10);
			}
			break;
		}
		sleep (10);
	}
	LLcalBlack(sLightLeft);
	LLcalBlack(sLightRight);

	playSound(soundBlip);

	displayBigTextLine(4, "  Done");

	sleep(1000);

}

//-------------------------------

void waitTouchRelease()
{
	displayBigTextLine(4, " START");

	while(true)
	{
		if (nNxtButtonPressed == 3)
		{
			while (nNxtButtonPressed == 3)
			{
				sleep (10);
			}
			break;
		}
		sleep (10);
	}
	eraseDisplay();
}
//---------------
int getRWLeft()
{
	tByteArray rawLight;
	tByteArray rawLight2;
	LLreadSensorRaw(sLightLeft, rawLight);
	MSLSAreadSensors(sLightLeft2, &rawLight2[0]);
	int r =
	(
	Min(rawLight[0], rawLight2[0]) +
	Min(rawLight[1], rawLight2[1]) +
	Min(rawLight[2], rawLight2[2]) +
	Min(rawLight[3], rawLight2[3]) +
	Min(rawLight[4], rawLight2[4]) +
	Min(rawLight[5], rawLight2[5]) +
	Min(rawLight[6], rawLight2[6]) +
	Min(rawLight[7], rawLight2[7])
	) ;
	if (( Min(rawLight[7], rawLight2[7]) < 10 ) && ( Min(rawLight[0], rawLight2[0]) > 10 )) r = r * -1;
	return r;
}
//--------------------
int getRWRight()
{
	tByteArray rawLight;
	tByteArray rawLight2;
	LLreadSensorRaw(sLightRight, rawLight);
	MSLSAreadSensors(sLightRight2, &rawLight2[0]);
	int r =
	(
	Min(rawLight[0], rawLight2[0]) +
	Min(rawLight[1], rawLight2[1]) +
	Min(rawLight[2], rawLight2[2]) +
	Min(rawLight[3], rawLight2[3]) +
	Min(rawLight[4], rawLight2[4]) +
	Min(rawLight[5], rawLight2[5]) +
	Min(rawLight[6], rawLight2[6]) +
	Min(rawLight[7], rawLight2[7])
	) ;
	if (( Min(rawLight[0], rawLight2[0]) < 10 ) && ( Min(rawLight[7], rawLight2[7]) > 10 )) r = r * -1;
	return r;
}
