#pragma config(Sensor, S4,     sLightLeft2,    sensorI2CCustom9V)
#pragma config(Sensor, S1,     sLightRight2,   sensorI2CCustom9V)
#pragma config(Sensor, S2,     sLightCenter,   sensorI2CCustom9V)
#pragma config(Motor,  motorB,          mLeft,         tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          mRight,        tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-lineleader.h"
#include "mindsensors-lightsensorarray.h"

// time: 	    08:20 - 08:40 (left) 8:60 - 8:80 (right) fast
// direction: left
// motors: 	  2
// ger: 	    direct
// tire:      \__/ #61481 + #56145c04

#define Max(x, y) (((x) > (y)) ? (x) : (y))
#define Min(x, y) (((x) < (y)) ? (x) : (y))

#define RELEASE
//#define DEBUG

void calibrate ();
void waitTouchRelease();
//--------------------
int vBase 			= 50;
int const vMax  = 50;

int const vMin	= 10;
int const k     = 25;
int iAlert			= 0;
bool leftAlert  = false;
bool rightAlert = false;
//--------------------
task speedUp()
{
	int vFinish        = vBase;
	int const vStart   = 30;
	int const tSpeedUp = 600;
	int tSleep = tSpeedUp / ( vFinish - vStart );

	for ( int i = vStart ; i <= vFinish ; i++ )
	{
		vBase = i ;
		sleep(tSleep);
	}
}

//--------------------
task main()
{

	MSLSAinit(sLightLeft2); 	// Set up Line Leader sensor type
	MSLSAinit(sLightRight2); 	// Set up Line Leader sensor type
	MSLSAsetEU(sLightLeft2); // European frequency compensation
	MSLSAsetEU(sLightRight2); // European frequency compensation

	LLinit(sLightCenter); 	// Set up Line Leader sensor type
	_lineLeader_cmd(sLightCenter, 'E'); // European frequency compensation

	calibrate();
	waitTouchRelease();
	startTask(speedUp);

	int eOld 				= 0;
	int e       		= 0;
	int u 					= 0;
	int v 				  = 0;
	int vLeft 			= 0;
	int vRight 			= 0;
	int centerLeft  = 0;
	int centerRight = 0;
	leftAlert  			= false;
	rightAlert 			= false;

	tByteArray rawLightLeft2;
	tByteArray rawLightRight2;
	tByteArray rawLightCenter;

	int leftLevel  = 0;
	int rightLevel = 0;

	while(true)
	{
		MSLSAreadSensors(sLightLeft2, &rawLightLeft2[0]);

		leftLevel = 8;
		for (int j = 0 ; j < 8; j++)
		{
			if (rawLightLeft2[j] < 20) break;
			leftLevel--;
		}

		MSLSAreadSensors(sLightRight2, &rawLightRight2[0]);

		rightLevel = 8;
		for (int j = 7 ; j >= 0; j--)
		{
			if (rawLightRight2[j] < 20) break;
			rightLevel--;
		}

		LLreadSensorRaw(sLightCenter, rawLightCenter);
		centerLeft =  (rawLightCenter[4] + rawLightCenter[5] + rawLightCenter[6] + rawLightCenter[7]);
		centerRight = (rawLightCenter[0] + rawLightCenter[1] + rawLightCenter[2] + rawLightCenter[3]);


	/*	displayBigTextLine(1,"l: %d", leftLevel);
		displayBigTextLine(3,"r: %d", rightLevel);
		displayBigTextLine(5,"la: %d", leftAlert);
		displayBigTextLine(7,"ra: %d", rightAlert);
		*/
		if (leftAlert == false)  leftAlert  = (leftLevel > 0);
		if (leftAlert && (iAlert > 0) && ((centerRight < 300) || (rightLevel > 0)))
		{
			leftAlert  = false;
			iAlert = 0;
		}

		if (rightAlert == false)  rightAlert = (rightLevel  > 0);
		if (rightAlert && (iAlert > 0) && ((centerLeft < 300) || (leftLevel > 0)))
		{
			rightAlert = false;
			iAlert = 0;
		}

		if (leftAlert)
		{
			if(leftLevel == 0) leftLevel = 8;
			vLeft  = vMax - (vMax - vMin) * leftLevel / 8 ;
			vRight = vMax ;
			iAlert ++;
		}
		else if (rightAlert)
		{
			if(rightLevel == 0)rightLevel = 8;
			vLeft  = vMax;
			vRight = vMax - (vMax - vMin) * rightLevel / 8 ;
			iAlert ++;
		}
		else
		{
			e =  centerLeft - centerRight;

			u = (e * 1  + (e - eOld ) * 7) / k; //+ i;
			v = (vBase - abs(u) * 0.3);//0.65 ) ;

			vLeft  = v + u;
			vRight = v - u;
			iAlert = 0;
		}

		if (vLeft  < vMin)  vLeft  = vMin;
		if (vRight < vMin)  vRight = vMin;
		if (vLeft  > vMax)  vLeft  = vMax;
		if (vRight > vMax)  vRight = vMax;

		eOld = e;

#ifdef RELEASE
		motor[mLeft]  = vLeft;
		motor[mRight] = vRight;
#endif
#ifdef DEBUG
	//	displayTextLine(0,"rwL %d",rwLeft);
	//	displayTextLine(1,"rwR %d", rwRight);
		displayTextLine(2,"lAlert %d", leftAlert);
		displayTextLine(3,"rAlert %d",rightAlert);
		displayTextLine(4,"e %d",e);
		displayTextLine(5,"u %d",u);
		displayTextLine(6,"vLeft %d",vLeft);
		displayTextLine(7, "vRight %d",vRight);
#endif
		sleep (1);
		//if (SensorValue(sTouch) == 1) break;
	}

	MSLSASleep(sLightLeft2);  // Sleep to conserve power when not in use
	MSLSASleep(sLightRight2); // Sleep to conserve power when not in use
}

//---------------------------------

void calibrate ()
{
	displayBigTextLine(4, "  WHITE");

	while(true)
	{
		if (nNxtButtonPressed == 3)
		{
			while (nNxtButtonPressed == 3)
			{
				sleep (10);
			}
			break;
		}
		sleep (10);
	}
	MSLSAcalWhite(sLightLeft2);
	MSLSAcalWhite(sLightRight2);
	LLcalWhite(sLightCenter);

	playSound(soundBlip);

	displayBigTextLine(4, "   Done");

	sleep(1000);

	displayBigTextLine(4, "CENTER BLACK");

	while(true)
	{
		if (nNxtButtonPressed == 3)
		{
			while (nNxtButtonPressed == 3)
			{
				sleep (10);
			}
			break;
		}
		sleep (10);
	}

		LLcalBlack(sLightCenter);

	sleep(1000);

	displayBigTextLine(4, "LEFT BLACK");

	while(true)
	{
		if (nNxtButtonPressed == 3)
		{
			while (nNxtButtonPressed == 3)
			{
				sleep (10);
			}
			break;
		}
		sleep (10);
	}
	MSLSAcalBlack(sLightLeft2);


	playSound(soundBlip);

	displayBigTextLine(4, "  Done");

	sleep(1000);

	displayBigTextLine(4, "RIGHT BLACK");

	while(true)
	{
		if (nNxtButtonPressed == 3)
		{
			while (nNxtButtonPressed == 3)
			{
				sleep (10);
			}
			break;
		}
		sleep (10);
	}
	MSLSAcalBlack(sLightRight2);

	playSound(soundBlip);

	displayBigTextLine(4, "  Done");

	sleep(1000);

}

//-------------------------------

void waitTouchRelease()
{
	displayBigTextLine(4, " START");

	while(true)
	{
		if (nNxtButtonPressed == 3)
		{
			while (nNxtButtonPressed == 3)
			{
				sleep (10);
			}
			break;
		}
		sleep (10);
	}
	eraseDisplay();
}
