#pragma config(Sensor, S4,     sLightLeft,     sensorI2CCustom9V)
#pragma config(Sensor, S3,     sLightLeft2,    sensorI2CCustom9V)
#pragma config(Sensor, S2,     sLightRight2,   sensorI2CCustom9V)
#pragma config(Sensor, S1,     sLightRight,    sensorI2CCustom9V)
#pragma config(Motor,  motorB,          mLeft,         tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          mRight,        tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-lineleader.h"
#include "mindsensors-lightsensorarray.h"

// time: 	    08:20 - 08:40 (left) 8:60 - 8:80 (right) fast
// direction: left
// motors: 	  2
// ger: 	    direct
// tire:      \__/ #61481 + #56145c04

#define RELEASE
//#define DEBUG
//--------------------
typedef struct power{
	byte left;
	byte right;
}power;
//--------------------
int getRWRight();
int getRWLeft();
void calibrate ();
void waitTouchRelease();
void safeToFile(power *p, int size);
//--------------------
int vBase 			= 50;
int const vMax  = 70;
int const vMin	= 10;
int const maxI	= 10;
float const k 	= 70;
int iAlert			= 0;
bool leftAlert  = false;
bool rightAlert = false;
//--------------------
bool recOn      = false;
power p[300];
//--------------------
task speedUp()
{
	int vFinish        = vBase;
	int const vStart   = 30;
	int const tSpeedUp = 600;
	int tSleep = tSpeedUp / ( vFinish - vStart );

	for ( int i = vStart ; i <= vFinish ; i++ )
	{
		vBase = i ;
		sleep(tSleep);
	}
}

//--------------------
task main()
{

	LLinit(sLightLeft); 	// Set up Line Leader sensor type
	LLinit(sLightRight); 	// Set up Line Leader sensor type
	MSLSAinit(sLightLeft2); 	// Set up Line Leader sensor type
	MSLSAinit(sLightRight2); 	// Set up Line Leader sensor type
	_lineLeader_cmd(sLightLeft, 'E'); // European frequency compensation
	_lineLeader_cmd(sLightRight, 'E'); // European frequency compensation
	MSLSAsetEU(sLightLeft2); // European frequency compensation
	MSLSAsetEU(sLightRight2); // European frequency compensation

	calibrate();
	waitTouchRelease();
	startTask(speedUp);

	int e       		= 0;
	int eOld 				= e;
	int rwLeft  		= getRWLeft();
	int rwRight 		= getRWRight();
	int es 					= rwLeft - rwRight;
	float i 				= 0;
	int 	v 				= 0 ;
	int   u					= 0 ;
	int vLeft 			= 0;
	int vRight 			= 0;
	long iSpeed     = 0;
	int iRec        = 0;
	leftAlert  			= false;
	rightAlert 			= false;
  tByteArray rawLightLeft;
	tByteArray rawLightLeft2;
	tByteArray rawLightRight;
	tByteArray rawLightRight2;

	clearTimer(T1);

	while(time1[T1] < 5000)
	{
		//------------
		LLreadSensorRaw(sLightLeft, rawLightLeft);
		MSLSAreadSensors(sLightLeft2, &rawLightLeft2[0]);

		rwLeft=
		(
		rawLightLeft[0] + rawLightLeft2[0] +
		rawLightLeft[1] + rawLightLeft2[1] +
		rawLightLeft[2] + rawLightLeft2[2] +
		rawLightLeft[3] + rawLightLeft2[3] +
		rawLightLeft[4] + rawLightLeft2[4] +
		rawLightLeft[5] + rawLightLeft2[5] +
		rawLightLeft[6] + rawLightLeft2[6] +
		rawLightLeft[7] + rawLightLeft2[7]
		);
		if ((rawLightLeft[7] < 10) && (rawLightLeft[0] > 10)) rwLeft = rwLeft * -1;
		//-----------------
		LLreadSensorRaw(sLightRight, rawLightRight);
		MSLSAreadSensors(sLightRight2, &rawLightRight2[0]);

		rwRight =
		(
		rawLightRight[0] + rawLightRight2[0] +
		rawLightRight[1] + rawLightRight2[1] +
		rawLightRight[2] + rawLightRight2[2] +
		rawLightRight[3] + rawLightRight2[3] +
		rawLightRight[4] + rawLightRight2[4] +
		rawLightRight[5] + rawLightRight2[5] +
		rawLightRight[6] + rawLightRight2[6] +
		rawLightRight[7] + rawLightRight2[7]
		);
		if ((rawLightRight[0] < 10) && (rawLightRight[7] > 10)) rwRight = rwRight  * -1;
		//-------------
		if ((rightAlert == false) && (rawLightLeft[7] < 20) && ((rawLightLeft[1] > 40) || (rawLightLeft[0] > 40))) leftAlert = true;
		if (leftAlert && (iAlert > 0)) leftAlert = ((rawLightLeft[4] > 20) &&
			(rawLightLeft[3] > 20) &&
		(rawLightLeft[2] > 20) &&
		(rawLightLeft[1] > 20) &&
		(rawLightLeft[0] > 20) &&
		(rawLightRight[0] > 20) &&
		(rawLightRight[1] > 20) &&
		(rawLightRight[2] > 20) &&
		(rawLightRight[3] > 20) &&
		(rawLightRight[4] > 20) &&
		(rawLightRight[5] > 20) &&
		(rawLightRight[6] > 20) &&
		(rawLightRight[7] > 20));
		if (leftAlert) rightAlert = false;

		if ((leftAlert == false) && (rawLightRight[0] < 20) && ((rawLightRight[6] > 40) || (rawLightRight[7] > 40))) rightAlert = true;
		if (rightAlert && (iAlert > 0)) rightAlert = ((rawLightRight[3] > 20) &&
			(rawLightRight[4] > 20) &&
		(rawLightRight[5] > 20) &&
		(rawLightRight[6] > 20) &&
		(rawLightRight[7] > 20) &&
		(rawLightLeft[0] > 20) &&
		(rawLightLeft[1] > 20) &&
		(rawLightLeft[2] > 20) &&
		(rawLightLeft[3] > 20) &&
		(rawLightLeft[4] > 20) &&
		(rawLightLeft[5] > 20) &&
		(rawLightLeft[6] > 20) &&
		(rawLightLeft[7] > 20));
		if (rightAlert) leftAlert = false;
		//--------------
		e = rwLeft - rwRight - es;

		if (leftAlert)
		{
			if (recOn == false) recOn = true;
			vLeft  = vMin;
			vRight = 90 ;
			iAlert ++;
		}
		else if (rightAlert)
		{
			if (recOn == false) recOn = true;
			vLeft  = 90;
			vRight = vMin;
			iAlert ++;
		}
		else
		{
			if ( iAlert != 0 )
			{
				i = 0;
				iSpeed = 0;
			}

			i = i + e / 2500;
			if ( fabs(i) > maxI ) i = sgn(i) * maxI ;
			u = (e * 1  + (e - eOld ) * 7) / k  + i;
			v = (vBase - abs (u) * 0.65 ) ;

			vLeft = v + u;
			vRight = v - u;

			iAlert = 0;
		}

		eOld = e ;

		if (vLeft  < vMin)  vLeft  = vMin;
		if (vRight < vMin)  vRight = vMin;
		if (vLeft  > vMax)  vLeft  = vMax;
		if (vRight > vMax)  vRight = vMax;

#ifdef RELEASE
		if (recOn)
		{
			p[iRec].left = vLeft;
			p[iRec].right = vRight;
			iRec++;
		}
		motor[mLeft]  = vLeft;
		motor[mRight] = vRight;
#endif
#ifdef DEBUG
		displayTextLine(0,"rwL %d",rwLeft);
		displayTextLine(1,"rwR %d", rwRight);
		displayTextLine(2,"lAlert %d", leftAlert);
		displayTextLine(3,"rAlert %d",rightAlert);
		displayTextLine(4,"e %d",e);
		displayTextLine(5,"u %d",u);
		displayTextLine(6,"vLeft %d",vLeft);
		displayTextLine(7, "vRight %d",vRight);
#endif
		sleep (1);
		//if (SensorValue(sTouch) == 1) break;
	}
	LLsleep(sLightLeft);  // Sleep to conserve power when not in use
	LLsleep(sLightRight); // Sleep to conserve power when not in use

	motor[mLeft]  = 0;
	motor[mRight] = 0;

	eraseDisplay();
	displayBigTextLine(4, "writting...");
	safeToFile(p, iRec + 1);
	displayBigTextLine(4, "  Done");
}

//---------------------------------

void calibrate ()
{
	displayBigTextLine(4, "  WHITE");

	while(true)
	{
		if (nNxtButtonPressed == 3)
		{
			while (nNxtButtonPressed == 3)
			{
				sleep (10);
			}
			break;
		}
		sleep (10);
	}
	LLcalWhite(sLightLeft);
	LLcalWhite(sLightRight);

	playSound(soundBlip);

	displayBigTextLine(4, "   Done");

	sleep(1000);

	displayBigTextLine(4, "  BLACK");

	while(true)
	{
		if (nNxtButtonPressed == 3)
		{
			while (nNxtButtonPressed == 3)
			{
				sleep (10);
			}
			break;
		}
		sleep (10);
	}
	LLcalBlack(sLightLeft);
	LLcalBlack(sLightRight);

	playSound(soundBlip);

	displayBigTextLine(4, "  Done");

	sleep(1000);
}

//-------------------------------

void waitTouchRelease()
{
	displayBigTextLine(4, " START");

	while(true)
	{
		if (nNxtButtonPressed == 3)
		{
			while (nNxtButtonPressed == 3)
			{
				sleep (10);
			}
			break;
		}
		sleep (10);
	}
	eraseDisplay();
}
//---------------
int getRWLeft()
{
	tByteArray rawLight;
	LLreadSensorRaw(sLightLeft, rawLight);
	int r =
	(
	rawLight[0]  +
	rawLight[1]  +
	rawLight[2]  +
	rawLight[3]  +
	rawLight[4]  +
	rawLight[5]  +
	rawLight[6]  +
	rawLight[7]
	) ;
	if (( rawLight[7] < 10 ) && ( rawLight[0] > 10 )) r = r * -1;
	return r;
}
//--------------------
int getRWRight()
{
	tByteArray rawLight;
	LLreadSensorRaw(sLightRight, rawLight);
	int r =
	(
	rawLight[0] +
	rawLight[1] +
	rawLight[2] +
	rawLight[3] +
	rawLight[4] +
	rawLight[5] +
	rawLight[6] +
	rawLight[7]
	) ;
	if (( rawLight[0] < 10 ) && ( rawLight[7] > 10 )) r = r * -1;
	return r;
}

void safeToFile(power *p, int size){

	TFileHandle hFile;
	TFileIOResult ioResult;
	string fileName = "r0.bin";
	short sizeFile = size * sizeof(power);

	Delete(fileName , ioResult);
	OpenWrite(hFile, ioResult, fileName, sizeFile);

	for (int i = 0 ; i < size; i++)
	{
		WriteByte(hFile, ioResult, p[i].left);
		WriteByte(hFile, ioResult, p[i].right);
	}

	Close(hFile, ioResult);
}
