#pragma config(Sensor, S1,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          mB,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	int errOld = 0;

	const float kp =1;
	const float kd =0;

	while(true)
	{
		int err = sonar - 30;
		int u = (kp * err) + (kd * (err - errOld));

		motor[mB] = 50 + u;
		motor[mC] = 50 - u;

		errOld = err;

		sleep(1);
	}

}
