#pragma config(Motor,  motorA,          mRotation,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mArm,          tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          mLandle,       tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void initArm();
void initLandle();

task main()
{

initArm();
initLandle();

}

void initLandle()
{
	int e = nMotorEncoder[mLandle];
	int eOld= e;
	motor[mLandle] = 10;
	sleep(30);
	while (true)
	{
		sleep(30);
		int e = nMotorEncoder[mLandle];
		if (e == eOld) break;
		eOld = e;
	}
	motor[mLandle] = 0;
	sleep(200);
	motor[mLandle] = -10;
	sleep(200);
	motor[mLandle] = 0;
}

void initArm()
{
	int e = nMotorEncoder[mArm];
	int eOld= e;
	motor[mArm] = -20;
	sleep(30);
	while (true)
	{
		sleep(30);
		int e = nMotorEncoder[mArm];
		if (e == eOld) break;
		eOld = e;
	}
	motor[mArm] = 0;
	sleep(200);
	motor[mArm] = 20;
	sleep(200);
	motor[mArm] = 0;
}
