#pragma config(Motor,  motorB,          mCenter,       tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define ENC_CENTER 1450

void GoAheadMM();
void GoBackMM();

task main()
{
	GoAheadMM();
	sleep(3000);
	GoBackMM();
}

void GoAheadMM(){
		nMotorEncoder[mCenter] =0;
		while(nMotorEncoder[mCenter] < ENC_CENTER){
			motor[mCenter] = 20;
		}
		motor[mCenter] = 0;
}

void GoBackMM(){
	nMotorEncoder[mCenter] =0;
		while(nMotorEncoder[mCenter] > -ENC_CENTER){
			motor[mCenter] = -20;
		}
		motor[mCenter] = 0;
}
