#pragma config(Motor,  motorA,          mLeft,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mRight,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define RIGHT_ENC 1105
#define LEFT_ENC 1105
#define CM5_ENC 244
#define CM40_ENC 1950 //1950
#define CM20_ENC 975
#define CM10_ENC 488

void TurnAntiClock();
void TurnClock();
void GoAheadMM(int dist);

task main()
{
	/*
	TurnAntiClock();
	sleep(3000);
	TurnClock();
	*/
	GoAheadMM(175);

}

void TurnAntiClock(){
	nMotorEncoder[mRight] =0;
	while(nMotorEncoder[mRight] < RIGHT_ENC){
		motor[mLeft] = -50;
		motor[mRight] = 50;
	}
	motor[mLeft] = 0;
	motor[mRight] = 0;
}

void TurnClock(){
	nMotorEncoder[mLeft] =0;
	while(nMotorEncoder[mLeft] < LEFT_ENC){
		motor[mRight] = -50;
		motor[mLeft] = 50;
	}
	motor[mRight] = 0;
	motor[mLeft] = 0;
}

void GoAheadMM(int dist){ //MM
		int enc = (CM40_ENC * dist) / 400;
		nMotorEncoder[mLeft] =0;
		while(nMotorEncoder[mLeft] < enc){
			motor[mRight] = 50;
			motor[mLeft] = 50;
		}
		motor[mRight] = 0;
		motor[mLeft] = 0;
}
