#pragma config(Sensor, S1,     s1,             sensorLightActive)
#pragma config(Sensor, S2,     s2,             sensorLightActive)
#pragma config(Sensor, S3,     s3,             sensorLightActive)
#pragma config(Sensor, S4,     s4,             sensorLightActive)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop, reversed, encoder)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, openLoop, reversed, encoder)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, openLoop, reversed, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task encoders ()
{
	while (true)
	{
		nMotorEncoder[motorA]=0;
		while (nMotorEncoder[motorA] >= -720)// while encoder <= -720
		{
			sleep (10);
		}
		playSound(soundBeepBeep);
	}
}
task main()
{
	startTask (encoders);
	SensorValue(s1) = 0;
	SensorValue(s2) = 0;
	SensorValue(s3) = 0;
	SensorValue(s4) = 0;

	int const v = 100;
	int  e = 0 , u = 0 , eOld = 0 , e1 = 0 , e2 = 0;

	nMotorEncoder[motorA]=0;

	while (true)
	{
		nMotorEncoder[motorA]=0;
		//	nMotorEncoder[motorB]=0;
		//	nMotorEncoder[motorC]=0;
		//	nMotorEncoder[motorD]=0;

		e1 = SensorValue(s1) * 2 + SensorValue(s2);
		e2 = SensorValue(s3) + SensorValue(s4) * 2;

		e = e1 - e2;

		u = (e + (e - eOld) * 10) * 2;

		eOld = e;

		motor[motorA]=v-u;
		motor[motorB]=v-u;
		motor[motorC]=v+u;
		motor[motorD]=v+u;
	}
}
