#pragma config(Sensor, S1,     s1,             sensorLightActive)
#pragma config(Sensor, S2,     s2,             sensorLightActive)
#pragma config(Sensor, S3,     s3,             sensorLightActive)
#pragma config(Sensor, S4,     s4,             sensorLightActive)
#pragma config(Motor,  motorA,          mLeft2,        tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          mLeft,         tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          mRight,        tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,          mRight2,       tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task TestSound ();
task TestEncoder();

task main()
{
	SensorValue(s1) = 0;
	SensorValue(s2) = 0;
	SensorValue(s3) = 0;
	SensorValue(s4) = 0;

	const int v = 100;
	int  e = 0 , u = 0 , eOld = 0 , e1 = 0 , e2 = 0;

	startTask(TestSound);

	while (true)
	{
		e1 = SensorValue(s1) * 2 + SensorValue(s2);
		e2 = SensorValue(s3) + SensorValue(s4) * 2;
		e = e1 - e2;
		u = (e + (e - eOld) * 10) * 2;
		eOld = e;

		motor[mLeft2]=v-u;
		motor[mLeft] =v-u;
		motor[mRight]=v+u;
		motor[mRight2]=v+u;

		sleep(10);
	}
}

task TestSound ()
{
	while ( true )
	{
		playSound(soundBeepBeep);
		sleep (1000);
	}
}

task TestEncoder()
{
	nMotorEncoder[mLeft2] = 0;
	while(nMotorEncoder[mLeft2] < (360))
	{
		sleep(10);
	}
	playSound(soundBeepBeep);
}
