#pragma config(Sensor, S1,     sLeft2,         sensorLightActive)
#pragma config(Sensor, S2,     sLeft,          sensorLightActive)
#pragma config(Sensor, S3,     sRight,         sensorLightActive)
#pragma config(Sensor, S4,     sRight2,        sensorLightActive)
#pragma config(Motor,  motorA,          mLeft2,        tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          mLeft,         tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          mRight,        tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,          mRight2,       tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void WaitTouchRealise();
void GetErrorAfterTouchRealise(float &eS, float &kCenter);
void ClearAllSensors();
//
task main()
{
	const int maxSpeed = 100;
	float eS = 0;
	float eOld = 0, u=0;


	//bFloatDuringInactiveMotorPWM = false;
	datalogClear();

	ClearAllSensors();
	GetErrorAfterTouchRealise(eS);
	WaitTouchRealise();

	eraseDisplay();

	while (true)
	{
		int e = SensorValue (sLeft) - SensorValue (sRight)- eS;

		//if ( sgn(eOld) != sgn(e) ) eOld=e;
		//if ( abs(eOld)  > abs(e) ) eOld=e;
		//int u =(e+(e-eOld)*14)*2.55;
		u =(e + ( e - eOld ) * 10 ) * 2 ;
		eOld = e;
		///////////////////////////////////////////
		displayBigTextLine(0, "e: %f", e);
		displayBigTextLine(2, "eOld: %f", eOld);
		displayBigTextLine(4, "u: %f", u);
		displayBigTextLine(6, "k: %f", k);

		datalogAddValueWithTimeStamp(0, e);
		datalogAddValueWithTimeStamp(1, u);
		datalogAddValueWithTimeStamp(2, k);
		///////////////////////////////////////////


		motor[mLeft]  = maxSpeed + u;
		motor[mRight] = maxSpeed - u;
		wait1Msec(1);


		void WaitTouchRealise ()
		{
			while (SensorValue(sTouch)== 0)
			{
				sleep (10);
			}
			while (SensorValue(sTouch)== 1)
			{
				sleep (10);
			}

		}

		void GetErrorAfterTouchRealise(float &eS, float &kCenter)
		{
			displayTextLine(1, "Press button to save error.");
			while(SensorValue(sTouch) == 0)
			{
				eS = SensorValue (sLeft) - SensorValue (sRight);
				kCenter =SensorValue (sCenter);
				displayBigTextLine(2, "Error: %f", eS);
				displayBigTextLine(4, "Center: %f", kCenter);
				sleep(10);
			}
			sleep(10);
			displayTextLine(1, "Release button to run.");
			while(SensorValue(sTouch) == 1)
			{
				sleep(10);
			}
		}

		void ClearAllSensors()
		{
			SensorValue (sTouch)=0;
			SensorValue (sLeft)=0;
			SensorValue (sRight)=0;
			SensorValue (sCenter)=0;
		}
