#pragma config(Sensor, S1,     sLeft,          sensorLightActive)
#pragma config(Sensor, S2,     sCenter,        sensorLightActive)
#pragma config(Sensor, S3,     sRight,         sensorLightActive)
#pragma config(Sensor, S4,     sTouch,         sensorEV3_Touch)
#pragma config(Motor,  motorC,          mLeft,         tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,          mRight,        tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void WaitTouchRealise();
void GetErrorAfterTouchRealise(float &eS, float &kCenter);
void ClearAllSensors();
//
task main()
{
	const int maxSpeed = 80;
	float eS = 0, kCenter = 0;
	float eOld = 0, k=0,  u=0;
	int v = 0;

	//bFloatDuringInactiveMotorPWM = false;
	datalogClear();

	ClearAllSensors();
	GetErrorAfterTouchRealise(eS , kCenter);
	WaitTouchRealise();

	eraseDisplay();

	while (true)
	{
		int e = SensorValue (sLeft) - SensorValue (sRight)- eS;

		//if ( sgn(eOld) != sgn(e) ) eOld=e;
		//if ( abs(eOld)  > abs(e) ) eOld=e;
		//int u =(e+(e-eOld)*14)*2.55;

		k =  1.85 ;//* (float)(SensorValue (sCenter) / kCenter);
		u =(e + ( e - eOld ) * 2 ) * k ;
		v = maxSpeed - abs(u) * 0.4;

		if ( abs(u) > v ) u = sgn(u) * v;
		///////////////////////////////////////////
		displayBigTextLine(0, "e: %f", e);
		displayBigTextLine(2, "eOld: %f", eOld);
		displayBigTextLine(4, "u: %f", u);
		displayBigTextLine(6, "k: %f", k);

		datalogAddValueWithTimeStamp(0, e);
		datalogAddValueWithTimeStamp(1, u);
		datalogAddValueWithTimeStamp(2, k);
		///////////////////////////////////////////
		eOld = e;

		motor[mLeft] = v + u;
		motor[mRight] = v - u;
		wait1Msec(1);
		if (SensorValue(sTouch)== 1) break;
	}
	motor[mLeft] = 0;
	motor[mRight] = 0;
}

void WaitTouchRealise ()
{
	while (SensorValue(sTouch)== 0)
	{
		sleep (10);
	}
	while (SensorValue(sTouch)== 1)
	{
		sleep (10);
	}

}

void GetErrorAfterTouchRealise(float &eS, float &kCenter)
{
	displayTextLine(1, "Press button to save error.");
	while(SensorValue(sTouch) == 0)
	{
		eS = SensorValue (sLeft) - SensorValue (sRight);
		kCenter =SensorValue (sCenter);
		displayBigTextLine(2, "Error: %f", eS);
		displayBigTextLine(4, "Center: %f", kCenter);
		sleep(10);
	}
	sleep(10);
	displayTextLine(1, "Release button to run.");
	while(SensorValue(sTouch) == 1)
	{
		sleep(10);
	}
}

void ClearAllSensors()
{
	SensorValue (sTouch)=0;
	SensorValue (sLeft)=0;
	SensorValue (sRight)=0;
	SensorValue (sCenter)=0;
}
