#pragma config(Sensor, S1,     sLightLeft,     sensorLightActive)
#pragma config(Sensor, S2,     sLightCenter,   sensorLightActive)
#pragma config(Sensor, S3,     sLightRight,    sensorLightActive)
#pragma config(Sensor, S4,     sTouch,         sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          mLeft,         tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          mRight,        tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//
// headers
//
int getLightensorsLeftRightDifferentByTouch();
//
task main()
{
	int eStart=getLightensorsLeftRightDifferentByTouch();


}


int getLightensorsLeftRightDifferentByTouch()
{
  nxtDisplayTextLine(1, "Stay at white area");
  nxtDisplayTextLine(2, "press button");

 	while(SensorValue(sTouch) == 0)
 	{

 		wait1Msec(100);
	}

	int diff=0;

	eraseDisplay();  // erase the entire NXT LCD display
	nxtDisplayTextLine(1, "Stay at white area");
  nxtDisplayTextLine(2, "release button");

	while(SensorValue(sTouch) == 1)
	{
		diff = SensorValue(sLightLeft) - SensorValue(sLightRight);

  	nxtDisplayTextLine(3, "Left:  %d", SensorValue(sLightLeft) );
  	nxtDisplayTextLine(4, "Right: %d", SensorValue(sLightRight));
  	nxtDisplayTextLine(5, "Diff:  %d", diff);
		wait1Msec(100);
	}
	PlaySound(soundBeepBeep);
	wait10Msec(500);
	return diff;

}
