#pragma config(Sensor, S1,     sLight,         sensorI2CCustom9V)
#pragma config(Sensor, S4,     sTouch,         sensorTouch)
#pragma config(Motor,  motorB,          mLeft,         tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          mRight,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-lineleader.h"
float GetLightError();

task main()
{

	while (SensorValue(sTouch)== 0)
	{
		sleep (10);
	}
	while (SensorValue(sTouch)== 1)
	{
		sleep (10);
	}

	int const vMax = 100;
	float es = GetLightError() ;
	float  e = 0;
	float eOld = e;

	while(true)
	{
		e = GetLightError() - es;

		float	u = e *3 - (e - eOld) * 10;

		eOld = e ;

		motor[mLeft] = vMax - u;
		motor[mRight] = vMax + u;

		sleep (1);
	}

}

float GetLightError()
{
	tByteArray light;
	LLreadSensorRaw(sLight, light); // read the raw sensor data (8 bit data)

	float e = ( light[0] - light[7] ) + ( light[1] - light[6] ) * 2 + ( light[2] - light[5] ) * 3 + ( light[3] - light[4] ) * 4;
	return e;
}
