#pragma config(Sensor, S1,     sIR,            sensorEV3_IRSensor)
//#pragma config(Sensor, S4,     sTouch,         sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void showResult();
void saveResult();

float r1 = 0;
float r2 = 0;
float r3 = 0;
float r4 = 0;
float r5 = 0;

task timerShow()
{
	while ( true )
	{
		displayBigTextLine(0, "%2.2f", (float)time1[timer1]/1000);
		sleep(50);
	}
}


task main()
{
	SensorValue(sIR) = 0;
	bool isRunning = false;
	displayBigTextLine(0, "waiting...");

	while (true)
	{
		int distance = SensorValue(sIR);


		if (( distance > 5 )  && ( distance < 40 ))
		{
			if (( isRunning ) && ( time1[timer1] < 2000 ))
			{
				sleep(2000);
				continue;
			}
			playSound( soundBlip );

			if ( isRunning )
			{
				saveResult();
			}
			else
			{
				clearTimer(timer1);
				startTask(timerShow);
			}
			isRunning = ! isRunning;
		}
		if(getButtonPress(2))
		{
			if (isRunning) saveResult();
			isRunning = false;
		}
		sleep(10);
	}

}

void saveResult()
{
	int r = time1[timer1];
	stopTask(timerShow);
	r5 = r4;
	r4 = r3;
	r3 = r2;
	r2 = r1;
	r1 = (float) r / 1000;
	showResult();
	displayBigTextLine(0, "waiting...");
}

void showResult()
{
	displayBigTextLine(3,  "   %2.3f", (float)r1);
	displayBigTextLine(5,  "   %2.3f", (float)r2);
	displayBigTextLine(7,  "   %2.3f", (float)r3);
	displayBigTextLine(9,  "   %2.3f", (float)r4);
	displayBigTextLine(11, "   %2.3f", (float)r5);
}
