#pragma config(Sensor, S1,     sRight2,        sensorLightActive)
#pragma config(Sensor, S2,     sRight,         sensorLightActive)
#pragma config(Sensor, S3,     sLeft,          sensorLightActive)
#pragma config(Sensor, S4,     sLeft2,         sensorLightActive)
#pragma config(Motor,  motorA,          mRight,        tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorB,          mCenter,       tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,          mLeft,         tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define RELEASE
#define DEBUG

task main()
{
	float es = 0;
	float e = 0;
	float eOld = e;
	float u = 0;
	int v = 0;

	int vLeft=0;
	int vRight=0;
	int vCenter=0;

	const int vMax = 100;


	es = ( SensorValue(sRight2) * 2 + SensorValue(sRight)) - (SensorValue(sLeft2) * 2 + SensorValue(sLeft));

	while(true)
	{
		e = ( SensorValue(sRight2) * 2 + SensorValue(sRight)) - (SensorValue(sLeft2) * 2 + SensorValue(sLeft)) - es;
		u = (e  + ( eOld - e )* 2)* 1.2 ;

		eOld = e;
		v = vMax - abs ( u * 1.1);
		vLeft=v+u/1.75;
		vRight=v-u/1.75;
		vCenter=u * 1.5;
#ifdef RELEASE
		motor[mLeft] = vLeft; //v + u ;
		motor[mRight] = vRight; //v - u;
		motor[mCenter] = vCenter;
#endif
#ifdef DEBUG
		displayVariableValues(0,u);
		displayVariableValues(1,v);
		displayVariableValues(2,vLeft);
		displayVariableValues(3,vRight);
		displayVariableValues(4,vCenter);
#endif
	}
}
