#pragma config(Sensor, S1,     sDistLeft,      sensorEV3_GenericI2C)
#pragma config(Sensor, S2,     sDistFront,     sensorEV3_GenericI2C)
#pragma config(Sensor, S3,     sDistRight,     sensorEV3_GenericI2C)
#pragma config(Sensor, S4,     sColor,         sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-irdist.h"

#define INIT_FRONT_DIST_MIN		100
#define INIT_FRONT_DIST_MAX		800
#define INIT_SIDE_DIST_MIN		300
#define INIT_SIDE_DIST_MAx		1500

int frontDistMin  = INIT_FRONT_DIST_MIN;
int frontDistMax	= INIT_FRONT_DIST_MAX;
int sideDistMin		= INIT_FRONT_DIST_MIN;
int sideDistMax		= INIT_FRONT_DIST_MAX;

int normalizeSide(int dist);
int normalizeFront(int dist);

int distRight = 0;
int distLeft  = 0;
int distFront = 0;

task getDist();

task main()
{
	startTask(getDist);

}

task getDist(){

	ubyte address = 0x02;

	string type1 = MSDISTreadModuleType(sDistFront, address);
	string type2 = MSDISTreadModuleType(sDistRight, address);
	string type3 = MSDISTreadModuleType(sDistLeft,  address);

	while(true){
		distRight = MSDISTreadDist(sDistFront, address);
		distLeft  = MSDISTreadDist(sDistLeft, address);
		distFront = MSDISTreadDist(sDistRight, address);
		sleep(100);
	}
}

int normalizeFront(int dist){
	if(dist < frontDistMin) return frontDistMin;
	if(dist > frontDistMax) return frontDistMax;
	return dist;
}

int normalizeSide(int dist){
	if(dist < sideDistMin) return sideDistMin;
	if(dist > sideDistMax) return sideDistMax;
	return dist;
}
