#pragma config(Sensor, S1,     MSDIST,         sensorI2CCustomFastSkipStates9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-irdist.h"

task main()
{

	while (true)
	{
		int dist1= MSDISTreadDist(MSDIST, 0x04);
		int dist2= MSDISTreadDist(MSDIST, 0x0C);
		displayTextLine(1, "%d", dist1);
		displayTextLine(2, "%d", dist2);

		sleep(50);
	}


}
