#pragma config(Sensor, S1,     sMuxA,         sensorI2CCustomFastSkipStates9V)
#pragma config(Sensor, S2,     sDistA3,       sensorI2CCustomFastSkipStates9V)
#pragma config(Sensor, S3,     sMuxB,         sensorI2CCustomFastSkipStates9V)
#pragma config(Sensor, S4,     sDistB3,       sensorI2CCustomFastSkipStates9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// includes
//
#include "mindsensors-irdist.h"

// defines
//
#define DEBUG
//
#define DIST_SHORT     150 		// calculates minimum distance for short distance sensor
#define INTERVAL_SMALL 10     // sleep interval for release car
#define INTERVAL_LONG  20     // sleep interval for new car

// headers
//
task counterA1();
task counterA2();
task counterA3();
/*
task counterB1();
task counterB2();
task counterB3();
*/
#ifdef DEBUG
task displayInfo();
#endif

// variables
//
int qA1 = 0; // first queue in the zone A
int qA2 = 0; // second queue in the zone A
int qB1 = 0; // first queue in the zone B
int qB2 = 0; // second queue in the zone B


task main()
{
	startTask(counterA1);
	sleep(100);
	startTask(counterA2);
	sleep(100);
	startTask(counterA3);
	/*
	startTask(counterB1);
	startTask(counterB2);
	startTask(counterB3);
	*/
#ifdef DEBUG
	startTask(displayInfo);
#endif
	while(true)
	{
		sleep(100);
	}
}

task counterA1()
{
	int d = 0 ;
	ubyte address = 0x04;
	string type = MSDISTreadModuleType(sMuxA, address);
	while(true)
	{
		do
		{
			sleep(INTERVAL_LONG);
			d = MSDISTreadDist(sMuxA, address);
		} while (d  >= DIST_SHORT  | d == -1);

		do
		{
			sleep(INTERVAL_LONG);
			d = MSDISTreadDist(sMuxA, address);
		} while (d  < DIST_SHORT  | d == -1);

		qA1++;
	}
}

task counterA2()
{
	int d = 0 ;
	ubyte address = 0x06;
	string type = MSDISTreadModuleType(sMuxA, address);
	while(true)
	{
		do
		{
			sleep(INTERVAL_LONG);
			d = MSDISTreadDist(sMuxA, address);
		} while (d  >= DIST_SHORT  | d == -1);

		do
		{
			sleep(INTERVAL_LONG);
			d = MSDISTreadDist(sMuxA, address);
		} while (d  < DIST_SHORT  | d == -1);

		qA1--;
		qA2++;
	}
}

task counterA3()
{
	int d = 0 ;
	ubyte address = 0x0c;
	string type = MSDISTreadModuleType(sMuxA, address);
	while(true)
	{
		do
		{
			sleep(INTERVAL_LONG);
			d = MSDISTreadDist(sMuxA, address);
		} while (d  >= DIST_SHORT  | d == -1);

		do
		{
			sleep(INTERVAL_LONG);
			d = MSDISTreadDist(sMuxA, address);
		} while (d  < DIST_SHORT  | d == -1);

		qA2--;
	}
}

task displayInfo()
{
	while(true)
	{
		displayTextLine(0,"A1= %d",qA1);
		displayTextLine(1,"A2= %d",qA2);
		displayTextLine(2,"B1= %d",qB1);
		displayTextLine(3,"B2= %d",qB2);
		sleep(100);
	}
}
