#pragma config(Sensor, S1,     sColor,         sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          mCon,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mSort,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task motorCon();

int greenValue;
int redValue;
int blueValue;

void turnRight();
void turnLeft();

task main()
{
	nMotorEncoder[mSort] =0;
	startTask(motorCon);
	while(true)
	{
		getColorRGB(sColor,redValue,greenValue,blueValue);
		displayBigTextLine(1,"%d",redValue);
		displayBigTextLine(3,"%d",greenValue);
		displayBigTextLine(5,"%d",blueValue);
		while(redValue < 10 && greenValue < 10 && blueValue < 10)
		{
			getColorRGB(sColor,redValue,greenValue,blueValue);
			displayBigTextLine(1,"%d",redValue);
			displayBigTextLine(3,"%d",greenValue);
			displayBigTextLine(5,"%d",blueValue);
			sleep(10);
		}
		if((15 < redValue < 30) && (greenValue < 15) && (5 < blueValue < 15)) turnLeft();//RED
		else if((15 < redValue < 25) && ( 35 < greenValue < 45) && (90 < blueValue < 100))turnRight();//YELLOW
		// Gnil or  ne gnil -- dima
	}
}

task motorCon()
{
	while(true)
	{
		motor[mCon] = 50;
		sleep(100);
	}
}

void turnRight()
{
	while(nMotorEncoder[mSort] < 0)
	{
		motor[mSort] = 20;
	}
}

void turnLeft()
{
	while(nMotorEncoder[mSort] < -68)
	{
		motor[mSort] = -20;
	}
}
