#pragma config(Sensor, S1,     sMUX,           sensorEV3_GenericI2C)
#pragma config(Motor,  motorB,          mLeft,         tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,          mRight,        tmotorNXT, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "mindsensors-rcxsensorsmux.h"
#include "mindsensors-ev3smux.h"

// The SMUX can have up to 3 sensors attached to it.
tMSEV3 muxedSensor[3];

// Configure your sensor type here.  The following are available:
// colorReflectedLight
// colorAmbientLight
// colorMeasureColor
// gyroAngle
// gyroRate
// infraRedProximity
// infraRedBeacon
// infraRedRemote
// sonarCM
// sonarInches
// sonarPresence
// touchStateBump

task main()
{

	initSensor(&muxedSensor[0], msensor_S1_1, sonarCM);
	initSensor(&muxedSensor[1], msensor_S1_2, sonarCM);
	initSensor(&muxedSensor[2], msensor_S1_3, touchStateBump);

	while ( true)
	{
		readSensor(&muxedSensor[0]);
		int c1 = muxedSensor[0].distance;

		readSensor(&muxedSensor[1]);
		int c2 = muxedSensor[1].distance;

		readSensor(&muxedSensor[2]);
		int c3 = muxedSensor[2].touch;

		displayTextLine(0, "left  :%d", c1);
		displayTextLine(1, "front :%d", c2);

		if ( c3 == 1 ) break;

		sleep (10);

	}
}
