#pragma config(Sensor, S1,     sSonarLeft,     sensorSONAR)
#pragma config(Sensor, S2,     sSonarFront,    sensorSONAR)
#pragma config(Sensor, S3,     sSonarRight,    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define RELEASE
#define DEBUG

task main()
{
	int const maxDist = 50;
	int vLeft 				= 50;
	int vRight 				= 50;

	while (true)
	{
		int sLeft = SensorValue(sSonarLeft);
		if (( sLeft < 3 )  || ( sLeft > maxDist))  sLeft  = 0;

		int sRight = SensorValue(sSonarRight);
		if (( sRight < 3 ) || ( sRight > maxDist)) sRight = 0;

		int sFront = SensorValue(sSonarFront);
		if (( sFront < 3 ) || ( sFront > maxDist)) sFront = 0;

		if (( sLeft > 0 ) && ( sFront > 0 ) && ( sLeft > 0 ))
		{
			vLeft 	= 100;
			vRight 	= 100;
		}
		else if (( sLeft > 0 ) && ( sFront > 0 ))
		{
			vLeft 	= 50;
			vRight 	= 100;
		}
		else if (( sRight > 0 ) && ( sFront > 0 ))
		{
			vLeft 	= 1000;
			vRight 	= 50;
		}
		else if ( sLeft > 0 )
		{
			vLeft 	= -50;
			vRight 	=  50;
		}
		else if ( sRight > 0 )
		{
			vLeft 	=  50;
			vRight 	= -50;
		}
		else if ( sFront > 0 )
		{
			vLeft 	= 100;
			vRight 	= 100;
		}
		else
		{
			// nothing to do
		}

#ifdef DEBUG
		displayTextLine(0, "left  :%d", sLeft);
		displayTextLine(1, "front :%d", sFront);
		displayTextLine(2, "right :%d", sRight);

		displayTextLine(3, "vLeft :%d", vLeft);
		displayTextLine(4, "vRight :%d", vRight);
#endif

		sleep(100);
	}

}
