#pragma config(Sensor, S4,     sLight,         sensorI2CCustom9V)
#pragma config(Motor,  motorA,          mShLeft,       tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          mLeft,         tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mRight,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          mShRight,      tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-lineleader.h"

void ShovelDown();
int GetLightAverage();

task main()
{

	ShovelDown ();
	eraseDisplay();

	int lightStart = GetLightAverage(); // data start
  int average = 0;
  while (true)
  {
  	average = GetLightAverage();
    displayBigTextLine(0, "%d", average);
  }

}

// retruns light average from 0 - black to 100 - white
int GetLightAverage()
{
		int average = 0;
	  int sensor = LLreadResult(sLight); // fetch the data from the sensor
	  tByteArray signalstr;

    LLreadSensorRaw(sLight, signalstr); // read the raw sensor data (8 bit data)

    for (int i = 0 ; i<8; i++)
    {
    	average += signalstr[i];
    }
    average /= 8;
    return average;
}


void ShovelDown()
{
	const int vShove =  50;
	const int dShove = -90;

	nMotorEncoder[mShLeft] = 0 ;
	nMotorEncoder[mShRight] = 0 ;
	motor[mShRight] = vShove ;
	motor[mShLeft] = vShove ;

	while((nMotorEncoder[mShRight] >= dShove ) & (nMotorEncoder[mShLeft] >= dShove ))
	{
  	sleep(1);
	}
	motor[mShRight] = 0 ;
	motor[mShLeft] = 0 ;

	displayBigTextLine(0, "%d", nMotorEncoder[mShRight]);
	displayBigTextLine(2, "%d", nMotorEncoder[mShLeft]);
	sleep(3000);
}
