#pragma config(Sensor, S1,     sRight,         sensorLightActive)
#pragma config(Sensor, S4,     sLeft,          sensorLightActive)
#pragma config(Motor,  motorB,          mRight,        tmotorEV3_Large, openLoop, reversed, encoder)
#pragma config(Motor,  motorC,          mLeft,         tmotorEV3_Large, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	sleep(5000);
	while(true)
	{

		if((SensorValue(sRight) > 42) | (SensorValue(sLeft) > 42))
		{
			motor[mLeft] = -100;
			motor[mRight] = -100;
			sleep(1000);
			motor[mLeft] = -50;
			motor[mRight] = 50;
			sleep(750);
		}
		else;
		{
			motor[mLeft] = 100;
			motor[mRight] = 100;
		}

	}
}
